=== clispecorg/clispec-monorepo/json-schema/clispec.schema.json
{
  "$id": "https://clispec.org/schema/draft/clispec.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "JSON schema for defining CLI interfaces",
  "type": "object",
  "$defs": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "simpleType": {
      "enum": [
        "string",
        "number",
        "integer",
        "boolean"
      ]
    },
    "option": {
      "type": "object",
      "description": "Опциональный параметр",
      "required": [
        "type"
      ],
      "x-additionalProperties": false,
      "properties": {
        "summary": {
          "type": "string",
          "description": "Короткое описание параметра"
        },
        "description": {
          "type": "string",
          "description": "Длинное описание параметра"
        },
        "type": {
          "oneOf": [
            {
              "description": "Фиксированное перечисление значений",
              "type": "array",
              "items": "string",
              "minItems": 1,
              "uniqueItems": true
            },
            {
              "description": "Простой тип значения",
              "$ref": "#/$defs/simpleType"
            },
            {
              "description": "",
              "type": "object",
              "properties": {
                "type": {
                  "$ref": "#/$defs/simpleType"
                },
                "boolean": {
                  "type": "boolean"
                }
              }
            }
          ]
        },
        "xxx-variadic": {
          "$comment": "TODO: Указать эту информацию в поле type, а также negatable",
          "type": "boolean",
          "description": "Параметр допускает задание нескольких значений"
        },
        "long": {
          "type": "string",
          "description": "Длинное имя опции: --<более одного символа>",
          "pattern": "^--[^-].+"
        },
        "short": {
          "type": "string",
          "description": "Короткое имя опции: -<один символ>",
          "pattern": "^-[^-]$"
        },
        "required": {
          "type": "boolean",
          "description": "Обязательный параметр",
          "default": false
        },
        "optionalValue": {
          "type": "boolean",
          "description": "Если true, значение можно не задавать, тогда типом значения будет boolean",
          "default": false
        },
        "negatable": {
          "type": "boolean",
          "description": "Разрешить для boolean значений использовать приставку --no"
        },
        "variadic": {
          "type": "boolean",
          "description": "Параметр допускает задание нескольких значений"
        },
        "standalone": {
          "type": "boolean",
          "description": "Автономный параметр не может быть использован совместно с другими параметрами. Например --version или --help",
          "default": false
        },
        "env": {
          "type": "string",
          "description": "Имя переменной окружения",
          "pattern": "^[A-Z0-9_]+"
        },
        "default": {
          "type": {},
          "description": "Значение по-умолчанию"
        },
        "pattern": {
          "type": "string",
          "description": "Регулярное выражение для значения",
          "format": "regex"
        },
        "hidden": {
          "type": "boolean",
          "description": "Скрытый параметр, не отображается в справке"
        }
      }
    }
  },
  "required": [
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "Имя команды",
      "pattern": ".+"
    },
    "summary": {
      "type": "string",
      "description": "Короткое описание команды"
    },
    "description": {
      "type": "string",
      "description": "Длинное описание команды"
    },
    "usage": {
      "type": "string",
      "description": "Строка описывающая как вызывать команду"
    },
    "hidden": {
      "type": "boolean",
      "description": "Скрытая команда, не отображается в справке"
    },
    "commands": {
      "type": "object",
      "patternProperties": {
        ".*": {
          "$ref": "#"
        }
      }
    },
    "options": {
      "type": "object",
      "patternProperties": {
        ".*": {
          "$ref": "#/$defs/option"
        }
      }
    }
  }
}

=== clispecorg/clispec-monorepo/json-schema/examples/git/clispec.json
{
  "$schema": "../../clispec.schema.json",
  "name": "git",
  "description": "Git version control system CLI",
  "options": {
    "name": {
      "name": "help",
      "description": "Получить справку",
      "type": "boolean",
      "short": "-h",
      "long": "--help",
      "standalone": true
    },
    "version": {
      "name": "version",
      "description": "Получить версию",
      "type": "boolean",
      "short": "-v",
      "long": "--version",
      "standalone": true
    }
  },
  "commands": {
    "fetch": {
      "description": "Download objects and refs from another repository",
      "options": {
        "append": {
          "name": "append",
          "type": "boolean",
          "default": false,
          "description": "Append ref names and object names of fetched refs to the existing contents of .git/FETCH_HEAD. Without this option old data in .git/FETCH_HEAD will be overwritten."
        },
        "depth": {
          "name": "depth",
          "type": "integer",
          "description": "Limit fetching to the specified number of commits from the tip of each remote branch history."
        },
        "negotiationTip": {
          "long": "--negotiation-tip",
          "env": "GIT_NEGOTIATION_TIP",
          "type": [
            "commit",
            "glob"
          ]
        }
      }
    }
  }
}

=== clispecorg/clispec-monorepo/json-schema/examples/pizza/clispec.json
{
  "$schema": "../../clispec.schema.json",
  "name": "pizza",
  "summary": "Git version control system CLI",
  "options": {
    "name": {
      "name": "help",
      "summary": "Получить справку",
      "type": "boolean",
      "short": "-h",
      "long": "--help",
      "standalone": true
    },
    "version": {
      "name": "version",
      "summary": "Получить версию",
      "type": "boolean",
      "short": "-v",
      "long": "--version",
      "standalone": true
    }
  },
  "commands": {
    "order": {
      "summary": "Создать новый заказ на пиццу",
      "options": {
        "cheese": {
          "type": "string",
          "optionalValue": true,
          "negatable": true,
          "summary": "Сыр",
          "long": "--cheese",
          "short": "-c"
        }
      }
    }
  }
}
